### ISSUE TITLE
Will kensa's 'test' command be replaced by addons-admin? 

### ISSUE THREAD

**Issue by simonc** [heroku/heroku-cli-addons-admin#41]
Hi there 👋 

I've been using kensa for some time now to test an addon I'm building. I'm now seeing a warning stating that kensa is deprecated in favor of addons-admin.

I was wondering if there was any plan to provide a command similar to `kensa test`. This part of kensa was critical in helping us verify our addon compatibility with Heroku (although the SSO test was not working with a non server-rendered solution).

Thanks! ❤️

**Comment by djcp** [comment]
@simonc 

Hello! We aren't planning on creating a `kensa test` equivalent in this project.  We instead suggest that you create a staging / development version of your add-on to do "full stack" testing against live Heroku APIs, leaving the staging add-on in alpha. This will hide it and keep it from accidentally billing for usage.

We document this in the [Building an Add-on](https://devcenter.heroku.com/articles/building-an-add-on#step-1-generate-your-add-on-manifest) devcenter article.

Part of the reason is that the Heroku partner APIs have moved beyond something that can be easily mocked out, and we weren't great at keeping kensa up-to-date for new features and API versions.

**Comment by djcp** [comment]
We're still transitioning from kensa to addons-admin, and I'm sorry for confusion during this transition. We're going to be doing a devcenter-wide documentation audit to clarify the new best practices.

**Comment by simonc** [comment]
@djcp Hi. Ok thank you for your answer 😊
